// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_times_within_periods
Rcpp::IntegerVector cpp_times_within_periods(Rcpp::NumericVector time_nums, Rcpp::NumericVector start_time_nums, Rcpp::NumericVector end_time_nums);
RcppExport SEXP _timeDF_cpp_times_within_periods(SEXP time_numsSEXP, SEXP start_time_numsSEXP, SEXP end_time_numsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_nums(time_numsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start_time_nums(start_time_numsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type end_time_nums(end_time_numsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_times_within_periods(time_nums, start_time_nums, end_time_nums));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_timeDF_cpp_times_within_periods", (DL_FUNC) &_timeDF_cpp_times_within_periods, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_timeDF(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
