# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.cpp_times_within_periods <- function(time_nums, start_time_nums, end_time_nums) {
    .Call(`_timeDF_cpp_times_within_periods`, time_nums, start_time_nums, end_time_nums)
}

